### ISSUE TITLE
Exception caught while writing new cache to ~/.feed2imap.cache.new: year too big to marshal

### ISSUE THREAD

**Issue by ruedigerp** [feed2imap/feed2imap#12]
Problem with cache:
1. Delete Cache files/dir

2. run feed2imap -c -v -f ~/.feed2imaprc  for rebuild the cache
    I, [2015-12-31T00:59:50.224838 #28352]  INFO -- : Finished. Saving cache ...
    F, [2015-12-31T00:59:50.226326 #28352] FATAL -- : Exception caught while writing new cache to /home/userXYZ/.feed2imap.cache.new: year too big to marshal

3. re-run feed2imap normal:
    /usr/bin/feed2imap -f -v ~/.feed2imaprc
    /usr/lib/ruby/vendor_ruby/feed2imap/cache.rb:84:in `load': end of file reached (EOFError)
    	from /usr/lib/ruby/vendor_ruby/feed2imap/cache.rb:84:in `load'
    	from /usr/lib/ruby/vendor_ruby/feed2imap/feed2imap.rb:87:in `initialize'
    	from /usr/lib/ruby/vendor_ruby/feed2imap/feed2imap.rb:86:in `open'
    	from /usr/lib/ruby/vendor_ruby/feed2imap/feed2imap.rb:86:in `initialize'
    	from /usr/bin/feed2imap:48:in `new'
    	from /usr/bin/feed2imap:48

**Comment by terceiro** [comment]
I can't reproduce this. please provide more information, e.g. which specific feed in your `~/.feed2imaprc` causes this.

**Comment by quite** [comment]
I got this here, which has a year -0001: https://dyn.com/blog/category/research/feed/
